server:
  port: 8787
spring:
#  main:
#    web-application-type: NONE
  server:
    datasource:
      jdbcUrl: jdbc:sqlite:data.db
      driverClassName: org.sqlite.JDBC
loggin:
  config: classpath:log4j2.xml